### ISSUE TITLE
google-services.json missing

### ISSUE THREAD

**Issue by unacorbatanegra** [covidpy/covidpy-app#1]
Hola!.
El archivo google-services.json está en falta.
Gracias!.

**Comment by miticge** [comment]
Buenas!
Se han subido archivos a modo de ejemplo:

          new file:   android/app/google-services.json
          new file:   ios/Runner/GoogleService-Info.plist

   Los archivos google service son utilizados en la app Flutter para las notificaciones push con Firebase. Puede ver más información en https://github.com/covidpy/covidpy-documentacion/blob/master/Arquitectura%20-%20COVID-19%20Paraguay.pdf  (página 49, 50) y documentación oficial Firebase: https://firebase.google.com/docs/cloud-messaging/.

Saludos.
--
fm
