### ISSUE TITLE
Background location

### ISSUE THREAD

**Issue by unacorbatanegra** [covidpy/covidpy-app#2]
Hola!, 

```
* What went wrong:                                                      
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Required by:                                                       
         project :app > project :flutter_background_geolocation  
```

![image](https://user-images.githubusercontent.com/44511181/90708084-fb5dee00-e266-11ea-80b3-a560561a07b0.png)

No esta especificada  la doc para esa sección.
Saludos.

**Comment by luiscard05** [comment]
Buenas,

La librería **flutter_background_geolocation** es utilizada para el reporte de ubicación del paciente. Puede ver más información en la documentación oficial de la librería utilizada donde se detalla la configuración para android y iOs.

**Link del repositorio oficial de transistorsoft - Configuración para android/iOs:**
[https://github.com/transistorsoft/flutter_background_geolocation/tree/master/help](https://github.com/transistorsoft/flutter_background_geolocation/tree/master/help)

**Link de la librería en Dart packages:**
[https://pub.dev/packages/flutter_background_geolocation](https://pub.dev/packages/flutter_background_geolocation)

Saludos

**Comment by unacorbatanegra** [comment]
Perfecto, gracias.
